# Docker on Travis requires sudo.
sudo: required

services:
  - docker

install:
  - BRANCH=`echo ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} | perl -pne 'chomp;s{.*/}{};s/\W/-/g'`
  - TAG=gehlenborglab/higlass-server:$BRANCH
  - echo $TAG
  - docker build --tag $TAG .

script:
  - docker run --name higlass-container --detach --publish 8001:8000 $TAG
  - JSON=`curl http://localhost:8001/`
  - echo $JSON
  - '[ "$JSON" == "{\"tilesets\":\"http://localhost:8001/tilesets/\"}" ] && echo "PASS"'
  # TODO: Test API and UI

# TODO: get bad image | after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - if [ "$TRAVIS_EVENT_TYPE" == 'pull_request' ]; then
  -   docker push $TAG
  - fi

after_failure:
  - docker logs higlass-container