# Docker on Travis requires sudo.
sudo: required

services:
  - docker

install:
  - echo $HOME
  - mkdir -p $HOME/.aws
  - >
      echo "[default]
      aws_access_key_id = $AWS_ACCESS_KEY_ID
      aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
      " > $HOME/.aws/credentials

script:
  - ./build.sh

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - >
      if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then
        echo "PR!";
      fi

  - >
      if [ ! -z "$TRAVIS_TAG" ]; then
        echo "Tagged $TRAVIS_TAG!";
        docker tag image $REPO:$TRAVIS_TAG;
      fi
