# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Docker publish

# on:
#   push:
#     tags:
#       - "v*"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ./test_runner.sh

  publish-docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build.sh -w 4
      - run: ./push.sh
        env:
          DOCKER_USER: higlass
          DOCKER_PASS: ${{secrets.DOCKER_PASS}}


